apiVersion: v2
name: defaultClusterIssuer
description: Default Cert Manager Cluster Issuer
type: application
version: 0.0.1
keywords:
  - defaultClusterIssuer
  - cert-manager
  - acme
sources:
  - https://github.com/lablabs/terraform-aws-eks-aws-cert-manager/blob/master/helm/defaultClusterIssuer/values.yaml
maintainers:
  - name: dojci
    email: martin.dojcak@lablabs.io
